### ISSUE TITLE
GPL?

### ISSUE THREAD

**Issue by wseltzer** [w3c/w3process-obsolete-rescinded#1]
If your first commit is a license, it should probably be the W3C Document License.

**Comment by wseltzer** [comment]
You can find better licensing info in https://github.com/w3c/licenses

**Comment by dwsinger** [comment]
having a hard time working out how this is related to documenting 'rescinded'...

**Comment by wseltzer** [comment]
@dwsinger https://github.com/w3c/w3process-obsolete-rescinded/blob/master/LICENSE in this repo. 
@koalie, can we change that?

**Comment by wseltzer** [comment]
uploaded better license file

**Comment by koalie** [comment]
(Thanks @wseltzer)
