### ISSUE TITLE
Process doesn't describe how to obsolete Rec

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3process-obsolete-rescinded#3]
The link to section 6.9 of the process only talks about rescinding rec, not obsoleting them. I assume this will be fixed if and when the new process gets adopted, but the document should probably be annotated in the meantime.

**Comment by dwsinger** [comment]
This page is explicitly to support the new (2016) process, and is not mentioned or linked to by the existing one.

**Comment by dontcallmedom** [comment]
yet it links to the current process and was announced without mention of the new process

**Comment by dwsinger** [comment]
It links to the standing place where the process lives. I don't think anyone will find this page until the (new) process is published that links to it, and even if they do, what harm is done?  I also don't want a version-specific mention of the process in here; that's asking for bitrot.  I don't see a problem here.

**Comment by dontcallmedom** [comment]
the page was announced to chairs today, and I assume that others might hit the same snag I did. but feel free to close the issue if you see it otherwise

**Comment by plehegar** [comment]
This will resolved itself on March 1st (once Process 2017 is effective). I'll send an update to the Chairs on March 1st.

**Comment by plehegar** [comment]
March 1st 2017 is passed.
